---
  - name: Print os facts
    hosts: all
    tasks:
      - name: Print OS
        debug:
          msg: "{{ ansible_distribution }}"
      - name: Print fact
        debug:
          msg: "{{ some_fact }}"
      - name: Print alternative fact
        debug:
          msg: "{{ some_fact_fed }}"
        when: ansible_distribution == "Fedora"